/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#aa0424',
        'primary-container': '#ce2939',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#410007',
        'on-primary-fixed-variant': '#92001d',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b1',
        'inverse-primary': '#ffb3b1',
        secondary: '#3f6748',
        'secondary-container': '#c0eec6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#446d4e',
        'secondary-fixed': '#c0eec6',
        'secondary-fixed-dim': '#a5d1ab',
        'on-secondary-fixed': '#00210c',
        'on-secondary-fixed-variant': '#274f32',
        tertiary: '#525454',
        'tertiary-container': '#6b6c6c',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#eeeeee',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        surface: '#fbf9f6',
        'surface-dim': '#dbdad7',
        'surface-bright': '#fbf9f6',
        'surface-variant': '#e4e2df',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f0',
        'surface-container': '#efeeeb',
        'surface-container-high': '#eae8e5',
        'surface-container-highest': '#e4e2df',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#5b403f',
        'on-background': '#1b1c1a',
        background: '#fbf9f6',
        outline: '#8f6f6e',
        'outline-variant': '#e3bebc',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-tint': '#ba172d',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
